---
- name: Install Jenkins on CentOS
  include_tasks: centos_jenkins.yaml
  when: 
    - ansible_os_family == "RedHat"

- name: Install Jenkins on Debian
  include_tasks: debian_jenkins.yaml
  when: 
    - ansible_os_family == "Debian"